title: Jawa motorcycles meetings
description: Your bike already, so where to go to meet other enthusiasts?
show_downloads: false
google_analytics: G-9WFL3P158G
theme: jekyll-theme-merlot
owner_url: https://www.kostecky.cz
owner_name: ivo@kostecky.cz